### ISSUE TITLE
Пожелания по улучшению

### ISSUE THREAD

**Issue by webmayak** [pantera-digital/yii2-site-dumper#1]
- [x] компонент `Dump` переименовать в `Dumper` и перенести в корень
- [x] для неймспейсов не использовать слеш в начале, т.е. просто `use Yii;` вместо `use \Yii;`
- [x] добавить папку `runtime` положить в нее `.gitignore`, соответственно убрать её из корневого `.gitignore`, не проверял, но, возможно, ругнется на отсутствие этой папки
- [x] удалить все незначимые (временные) комментарии, т.е. обеспечить чистоту кода

**Comment by mature-woman** [comment]
Сделано
